runtime: python27
api_version: 1
threadsafe: true

libraries:
#- name: webapp2
#  version: "latest"
#- name: jinja2
#  version: "latest"

skip_files:
  - ^(.*/)?app\.yaml
  - ^(.*/)?app\.yml
  - ^(.*/)?index\.yaml
  - ^(.*/)?index\.yml
  - ^(.*/)?#.*#
  - ^(.*/)?.*~
  - ^(.*/)?.*\.py[co]
  - ^(.*/)?.*/RCS/.*
  - ^(.*/)?\..*
  - ^(.*/)?tests$
  - ^(.*/)?test$
  - ^Makefile
  - ^COPYING.LESSER
  - ^README.rdoc
  - \.gitignore
  - ^\.git/.*
  - \.*\.lint$
  - \.backup/
  - ^Responsive_Assets


handlers:
  - url: /robots.txt
    static_files: static/robots.txt
    upload: static/img/robots.txt

  - url: /Responsive_Assets
    static_dir: Responsive_Assets
    login: admin
